src/VirtualFile.h
src/drawing.h
src/oslib.h

Before this pull request, building a project (even the samples included in oslibmodv2) would produce errors such as:
```
/usr/lib/gcc/psp/9.3.0/../../../../psp/lib/libosl.a(oslGetImagePixel.o):/home/seeseemelk/.cache/yay/psp-oslib/src/oslibmodv2/src/drawing.h:969: multiple definition of `oslUncacheImageData'
bin/main.o:/usr/psp/include/oslib/drawing.h:969: first defined here
/usr/lib/gcc/psp/9.3.0/../../../../psp/lib/libosl.a(oslGetImagePixel.o):/home/seeseemelk/.cache/yay/psp-oslib/src/oslibmodv2/src/drawing.h:1252: multiple definition of `oslImageIsCopySet'
bin/main.o:/usr/psp/include/oslib/drawing.h:1252: first defined here
/usr/lib/gcc/psp/9.3.0/../../../../psp/lib/libosl.a(oslGetImagePixel.o):/home/seeseemelk/.cache/yay/psp-oslib/src/oslibmodv2/src/drawing.h:1260: multiple definition …
```

Fix 'multiple definitions of...' errors

---

src/Special/oslLoadImageFile.c
src/Special/oslLoadImageFilePNG.c

- Adjusted the loop condition to use `sizeof(extension) - 1` instead of `-2`, allowing the full extension to be copied while still ensuring space for a null terminator.
- Initialized the `extension` buffer with zeros, removing the need for manual null termination after the loop.
- Ensured the code handles edge cases such as the extension being at the start of the filename.

Improve oslLoadImageFile function for better safety and extensibility

---

src/drawing.c
src/drawing.h

This PR introduces several code improvements and documentation enhancements to the OSLib codebase, focusing on better code clarity, maintainability, and performance. Key changes include the addition of inline setter functions for image flags, improved documentation for low-level drawing functions, and the introduction of vertex types for optimized rendering.
1. **Image Flag Management**:
- Added inline setter functions for managing image flags such as `oslImageIsCopySet`, `oslImageIsSwizzledSet`, and `oslImageSetAutoStrip`. These functions improve code readability and encapsulate flag manipulation, reducing the risk of errors.
- Updated macros for checking image flags, such as `oslImageIsCopy`, `oslImageIsSwizzled`, and `oslImageGetAutoStrip`.
2. **Texturing Functions**:
- Improved the …

Code Improvements and Documentation Enhancements for OSLib

---

src/osk.h

**Description:**
This PR documents the On-Screen Keyboard (OSK) support for PSP applications. Key features include:
- **OSK Structure:** Added `OSL_KEYBOARD` struct to handle OSK parameters.
- **Initialization:** Functions to initialize (`oslInitOskEx`) and configure OSK data (`oslInitOskDataEx`).
- **Activation/Deactivation:** Added functions to activate (`oslActivateOskEx`), check status (`oslOskIsActiveEx`), and deactivate (`oslDeActivateOskEx`) the OSK.
- **Result Handling:** Functions to get OSK results (`oslOskGetResultEx`) and output text (`oslOskOutTextEx`).
- **Basic OSK Functions:** Simplified initialization (`oslInitOsk`), drawing (`oslDrawOsk`), and termination (`oslEndOsk`) methods.
- **Backward Compatibility:** Maintains legacy support with `OSL_OSK_CANCEL`, …

Document OSK

---

src/messagebox.h

**Added Doxygen documentation to `messagebox.h`**
- Fully documented the `messagebox.h` file using Doxygen format.
- Provided detailed descriptions for all enums, macros, and functions.
- Included example usage for key macros like `oslDebug`, `oslMake3Buttons`, and `oslAssert`.
- Ensured that all public-facing components are documented without omitting any details.
This documentation will enhance code readability and maintainability by providing clear, in-code references for developers.

Document Messagebox

---

src/keys.h

The `OSL Keys` module in OSLib handles controller and remote inputs, offering key state management, auto-repeat functionality, and analog stick handling.
- **OSL_KEYLIST / OSL_CONTROLLER**: Structures for tracking controller button states (held, pressed, released) and analog stick positions.
- **OSL_REMOTEKEYLIST / OSL_REMOTECONTROLLER**: Similar structures for remote controllers.
- **oslSetKeyAutorepeat**: Configures auto-repeat for keys.
- **oslSetKeyAnalogToDPad**: Maps analog stick movements to D-pad inputs.
- **oslReadKeys**: Updates the `osl_pad` structure with the current controller state.
- **oslWaitKey / oslKbhit**: Waits for or checks if a key is pressed.
- **oslFlushKey**: Clears the key buffer.
- **oslReadRemoteKeys**: Updates the remote controller state.
- Supports …

Document Keys

---

src/map.h

This PR adds Doxygen documentation to the `map.h` file. The documentation covers the following:
- **OSL_MAP Structure**: Details the map structure, including tileset images, scrolling, tile sizes, and formats.
- **Enumerations**:
- `OSL_MAP_FORMATS`: Defines available map formats such as 16-bit and GBA-specific formats.
- `OSL_MAP_FLAGS`: Outlines internal map flags like transparency and drawing methods.
- **Functions**:
- `oslCreateMap()`: Describes how to create a new map with specified tileset and format.
- `oslDrawMap()`: Details the method for rendering a map on the screen.
- `oslDrawMapSimple()`: Provides backward compatibility for drawing maps (deprecated).
- `oslDeleteMap()`: Explains the procedure for deleting a map and managing associated memory.
The added documentation ensures …

Document Map

---

src/oslmath.h

This PR enhances the documentation for the OSLib Math functions, which utilize the PSP's Vector Floating Point Unit (VFPU). The updates include:
- **Improved Clarity:** Each function's purpose, parameters, and return values are now clearly explained, making it easier for developers to understand the functionality and expected behavior.
- **Consistency:** The format and language across all function descriptions have been standardized to ensure uniformity throughout the header file.
- **Additional Details:** Relevant information, such as input ranges, specific behaviors, and edge cases, has been added where applicable to provide a comprehensive understanding of each function.
- **Enhanced Readability:** Grammar and stylistic improvements have been made to enhance the overall readability and …

Document oslmath

---

src/saveload.h

**Add Save/Load Dialog Functionality with Documentation**
This PR introduces the `SaveLoad` module, enabling save, load, and delete operations with the following features:
- **Dialog Initialization:** Functions to initialize save, load, and delete dialogs, including multi-list, single, and automatic options.
- **Data Structure:** The `oslSaveLoad` struct, which holds all relevant data like game title, save name, and associated assets (icons, images).
- **Lifecycle Management:** Functions to manage dialog display, status retrieval, and finalization.
- **Doxygen Documentation:** Full documentation for easy integration and understanding.
This update streamlines game save/load management with a well-documented, flexible interface.

Document SaveLoad

---

src/sfont.h

This PR introduces Doxygen documentation for the `sfont.h` header file, which defines structures and functions for managing SFonts in the OSLib. The documentation covers the entire file, including detailed descriptions of each struct and function. This enhancement improves code readability and provides developers with a clear understanding of the SFont-related APIs.
- Added Doxygen comments to the `sfont.h` file.
- Documented the `OSL_SFLETTER` and `OSL_SFONT` structs.
- Provided descriptions for functions including `oslLoadSFontFile`, `oslDeleteSFont`, `oslGetSFontTextWidth`, and `oslSFontDrawText`.
- Ensured all elements within the file are properly documented without skipping any content.
- Improves documentation quality for better maintainability and ease of use.
- Helps developers …

Document SFont

---

src/text.h

This PR enhances the Doxygen documentation for the `text.h` file in OSLib, providing clearer and more detailed explanations for all text-related functions, structures, and macros. 
**Key Updates:**
- Added file-level overview and grouped related functions under a `@defgroup`.
- Detailed `@brief`, `@param`, and `@return` tags for all functions.
- Documented all structs and macros with inline comments.
- Expanded coverage to include intraFont-related functions.
These updates improve code readability and help developers quickly understand and utilize the text handling features in OSLib.

Document Text

---

src/usb.h

This PR enhances the documentation for the `usb.h` file using Doxygen, ensuring comprehensive coverage of all elements, including functions, macros, and enums. The documentation now provides clear descriptions of the purpose, usage, and return values for each function, as well as detailed information on the USB state enum and the `oslGetUsbState` macro.
- **File Overview**: Added a `@file` tag to provide a brief overview of the `usb.h` file's purpose.
- **Function Documentation**: Each USB function (`oslInitUsbStorage`, `oslStartUsbStorage`, `oslStopUsbStorage`, and `oslDeinitUsbStorage`) is now fully documented, with clear descriptions and return values.
- **Enum Documentation**: Documented the USB state enum, explaining the different possible states of the USB connection.
- **Macro …

Document usb

---

src/vfpu.h

This PR introduces a set of optimized mathematical functions that leverage the PSP's Vector Floating Point Unit (VFPU) for fast computation of trigonometric operations. The main functions added are:
- `oslVfpu_sinf`: Calculates the sine of an angle (in radians) multiplied by a radius.
- `oslVfpu_cosf`: Calculates the cosine of an angle (in radians) multiplied by a radius.
These functions are specifically designed for high performance on the PSP platform, making them ideal for scenarios requiring efficient trigonometric calculations.
- **Optimized for PSP:** Uses the VFPU, ensuring very fast execution.
- **Trigonometric Calculations:** Provides sine and cosine functions with support for radians and a scaling radius.
- **Doxygen Documentation:** The code is fully documented, facilitating …

Document vfpu

---

src/vram_mgr.h

Added Doxygen documentation to `vram_mgr.h`, covering all macros, global variables, and functions related to VRAM management in OSLib.
- **Macros**: Documented `OSL_VRAM_SIZE`, `OSL_VRAM_BASE`, and `OSL_VRAM_END`.
- **Global Variables**: Added descriptions for `osl_useVramManager` and `osl_currentVramPtr`.
- **Functions**:
- `oslVramMgrInit()`: Initializes the VRAM manager.
- `oslVramMgrAllocBlock(int blockSize)`: Allocates a block of VRAM.
- `oslVramMgrFreeBlock(void *blockAddress, int blockSize)`: Frees a VRAM block.
- `oslVramMgrSetParameters(void *adrStart, int size)`: Configures VRAM parameters.
This improves code clarity and aids future maintenance.

Document vram_mgr

---

src/adhoc/pspadhoc.h

This PR adds Doxygen documentation to the `pspadhoc.h` header file, covering all key aspects:
- **Error Codes & Connection States**: Clear definitions and descriptions for AdHoc error codes and connection states.
- **Remote PSP Structure**: Detailed documentation of the `remotePsp` structure, including MAC address, nickname, and connection state.
- **Function Descriptions**: Each function is documented with its purpose, parameters, and return values.
These updates improve code clarity and make it easier for developers to understand and use the AdHoc module.

Document pspadhoc

---

src/ccc.h

This PR adds `ccc.h`, a header file for character code conversion in OSLib, using BenHur's intraFont functions. It includes macros for converting various encodings (Shift JIS, GBK, Korean, BIG5, UTF-8) to UCS2, setting an error character, and shutting down the library.
- `oslCccSJIStoUCS2`, `oslCccGBKtoUCS2`, `oslCccKORtoUCS2`, `oslCccBIG5toUCS2`, `oslCccUTF8toUCS2`, `oslCccCodetoUCS2`: Convert different encodings to UCS2.
- `oslCccSetErrorCharUCS2`: Set the error character for failed conversions.
- `oslCccShutDown`: Shutdown the Character Code Conversion Library.
---
This PR introduces key functions for encoding conversions in OSLib, with clear Doxygen documentation for easy reference.

Document ccc

---

src/image/oslSwizzleImage.c

- Enhanced `oslSwizzleTexture` function with improved readability, loop structure, and consistency in variable usage.
- Added safety check for memory allocation failure in `oslSwizzleImage` function to handle errors gracefully.
- Improved documentation and added comments for better understanding of swizzling logic.
- Standardized pixel width calculations across functions for consistency.
- Cleaned up redundant code and made minor optimizations in the swizzling process.

Refactor and Improve Swizzling Functions in OSLib

---

src/image/oslGetImagePixel.c

- Added early boundary checks for x and y coordinates to prevent unnecessary processing.
- Simplified switch-case structure and improved 4-bit pixel format handling.
- Enhanced error handling for unsupported pixel formats.
- Ensured the function returns -1 for out-of-bounds or unsupported cases.

Optimized oslGetImagePixel function for better readability and performance

---

src/image/oslLockImage.c

- Enhanced comments to better describe the purpose and behavior of the functions.
- Reformatted code for consistent alignment and readability.
- Renamed variables to follow a more consistent naming convention (`bTextureEnabled` to `textureEnabled`, `bBlendingEnabled` to `blendingEnabled`).
- Clarified platform-specific operations with proper separation between PSP and non-PSP code.

Improve oslLockImage and oslUnlockImage functions for clarity and readability

---

src/image/oslSetDrawBuffer.c

Refactored the `oslSetDrawBuffer` function to enhance readability and maintainability without altering its core functionality.
- **Improved Comments:** Added clear explanations for each operation, focusing on the differences between PSP and non-PSP environments.
- **Streamlined Logic:** Grouped condition checks for better clarity and reduced redundancy.
- **Better Formatting:** Updated code indentation and spacing for improved readability.
Functionality remains unchanged, but the code is now easier to understand and maintain.

Refactor oslSetDrawBuffer function for improved readability and maintenance

---

src/image/oslConvertImageTo.c

This PR refactors the image conversion and palette search functions in `oslib` for better readability and maintainability.
- Improved variable naming for clarity.
- Added comments to explain key sections of the code.
- Introduced early return for better error handling during image creation.
- Refactored loops and conditionals for more readable code.
- Ensured proper cleanup of resources after image conversion.
- No changes to existing functionality.
- Code is now easier to understand and maintain.

Refactor image conversion and palette search functions for clarity and efficiency

---

src/image/oslScaleImage.c

Refactored the `oslScaleImageCreate` function to enhance readability and efficiency by simplifying the code structure and improving error handling.
- Implemented early returns to reduce nesting.
- Removed redundant `NULL` checks after image creation.
- Streamlined the flow of operations for better clarity.
No functional changes; the refactor improves maintainability and ensures consistent behavior in edge cases.

Refactor oslScaleImageCreate function for improved readability and efficiency

---

src/image/oslSetImagePixel.c

Refactored the `oslSetImagePixel` function to improve clarity and robustness.
- Simplified bounds checking with an early return for out-of-bounds pixels.
- Ensured type safety with explicit casts for pixel value assignments.
These changes enhance maintainability and readability without altering the function's behavior.

Refactor oslSetImagePixel function for clarity and robustness

---

src/image/oslSwizzleImage.c
src/image/oslUnswizzleImage.c

This PR improves the `oslUnswizzleTexture` and `oslUnswizzleImage` functions by enhancing code clarity, memory management, and platform-specific handling.
- Improved variable names for better readability.
- Added error handling for memory allocation in `oslUnswizzleImage`.
- Clarified platform-specific code for non-PSP environments.
- Preserved optimized loop structure for PSP performance.
These changes enhance the maintainability and robustness of the code without altering its existing functionality.

Improve oslUnswizzleTexture and oslUnswizzleImage functions

---

.gitignore
CMakeLists.txt
Platform/PSP.cmake

This PR finalizes and refines the CMake-based build system for the OSLib project, ensuring a reliable and maintainable setup tailored for PSP development. Key configurations and enhancements have been implemented to streamline the build process and improve cross-compilation support.
- **CMake Configuration**: 
- Introduced a modular CMake setup, defining the `libosl.a` static library as the main output.
- All relevant source files and directories are correctly included, with specific handling for assembly files.
- Ensured that the `.a` file is outputted directly in the project root directory.
- **PSP Toolchain Integration**:
- Created and utilized a `Platform/PSP.cmake` file to manage PSP-specific toolchain settings.
- Configured the C and C++ compilers, assembler, and common PSP …

Finalize CMake setup for OSLib project

---

src/vfile/vfsFile.c

This PR refactors the VFS file operations to improve code readability, maintainability, and ensure consistent behavior across file operations. Key changes include:
- **Refactored core file operations**: 
- Simplified `vfsFileOpen`, `vfsFileClose`, `vfsFileRead`, `vfsFileWrite`, `vfsFileSeek`, and `vfsFileTell`.
- Ensured proper handling of file modes (read, write, read/write) and resource cleanup.
- **Memory-based fallbacks**: 
- Integrated `vfsMemGetc`, `vfsMemPutc`, `vfsMemGets`, and `vfsMemPuts` as fallbacks for standard I/O functions.
- **Improved EOF handling**: 
- Added clear EOF flag management after read and seek operations.
- **Code cleanup**: 
- Reduced redundancy, used consistent return types, and streamlined function logic.
These changes enhance the overall structure and …

Refactor VFS file operations for improved readability and consistency

---

src/dialog.c

This PR improves the dialog handling logic in OSLib by refactoring and optimizing various functions for better readability, maintainability, and safety. Key changes include:
- **Improved error handling**: Ensured that all return values from `sceUtility*` functions are checked and handled appropriately. This avoids ignoring potential errors during dialog initialization and updates.
- **Buffer overflow prevention**: Replaced `strcpy` with `strncpy` to safely copy message strings and prevent buffer overflows.
- **Enhanced `oslDrawDialog`**: Improved logic for drawing dialogs, managing their states, and handling multiple dialog types (message, error, network, OSK, save/load, and browser dialogs).
- **Optimized state management**: Simplified the code for managing dialog states (`dialogType` …

Refactor and enhance Dialog handling in OSLib for improved safety and eficiency

---

src/vfile/VirtualFile.c

- Correctly handle memory allocation in oslReadEntireFileToMemory:
- Standardize memory block handling with BLOCK_SIZE macro for consistent allocation.
- Enhance error handling throughout the VirtualFile functions to ensure proper memory cleanup.
- Add comments for clarity and consistency in error handling and memory allocation logic.
- Ensure safe buffer management in functions like vfsMemGets to prevent buffer overflows.

Refactor VirtualFile memory management and enhance robustness

---

samples/map/main.c
src/map.c

- **oslDeleteMap**: Added null-check to prevent memory leaks when freeing uninitialized maps.
- **oslDrawMap**:
- Optimized tile index calculation with bitwise shifts for `tilesPerLineOpt`.
- Handled GBA-specific flags (flipping) in `OSL_MF_U16_GBA`.
- Fixed transparency handling with `firstTileOpaque` for alpha-blended tiles.
- Improved memory handling and rendering performance by reducing redundant drawing calls.
- **oslCreateMap**:
- Added validation for map data, dimensions, and formats.
- Initialized map properties and added error handling for invalid formats and allocation failures.

Refactor Map

---

src/oslHandleLoadNoFailError.c
src/vfpu.c

- Replaced magic numbers with named constants (e.g., DEG_TO_RAD for degree-to-radian conversion).
- Improved readability with more meaningful comments.
- Cleaned up VFPU wrapper functions (oslVfpu_sinf, oslVfpu_cosf, oslCos, oslSin).
- Grouped VFPU macros and constants for better maintainability.
- Optimized non-PSP trigonometric functions by directly using sinf and cosf.

Refactor VFPU trigonometric functions and optimize non-PSP implementations

---

src/audio/bgm.c

- Improved consistency in variable and function naming for better readability
- Refactored error handling logic to reduce redundancy and centralize cleanup
- Enhanced comments for better explanation of key functions and logic
- Extracted repeated and complex logic into smaller, more focused functions
- Removed unnecessary and unused code to streamline the implementation

Refactor ADPCM audio decoding and BGM sound callbacks

---

src/audio/audio.c

- Fix potential uninitialized variable issue in `oslDecodeWav` by initializing `streambuffer` to NULL and checking before freeing it.
- Add null checks and improve error handling in `oslAudioCallback_PlaySound_WAV`, `oslAudioCallback_AudioCallback_WAV`, `oslAudioCallback_ReactiveSound_WAV`, and `oslAudioCallback_StandBy_WAV`.
- Improve `oslAudioCallback_DeleteSound_WAV` with added null safety and proper memory management.
- Refactor `oslLoadSoundFileWAV` for better error handling, memory safety, and readability, including consolidated error handling and memory deallocation in case of failure.

Refactor and improve audio system

---

src/sfont.c

- Improved memory management and error handling in _loadFromPNG, oslLoadSFontFile, oslDeleteSFont, oslGetSFontTextWidth, and oslSFontDrawText.
- Added proper resource cleanup in case of failure.
- Used const correctness where appropriate.
- Simplified code structure and improved readability.
- Added bounds checking and null checks for safer code.

Refactored PNG loading and SFont handling

---

src/oslib.c

- Replaced magic numbers with meaningful constants for better readability.
- Modularized common logic in trigonometric and frame sync functions.
- Improved naming conventions and added descriptive comments.
- Optimized input validation in trigonometric functions (angle handling).
- Simplified frame synchronization logic and added support for dynamic frameskip and VSync.
- Completed system initialization and PSP-specific callback setup.
- Enhanced the benchmarking utilities for more accurate performance measurements.
- Improved memory alignment and optimized memset for hardware acceleration.

Refactor OSLib
