- src/net.h
This is the only change needed for it to build. I have not tested using it.
> Make oslib build with newer PSP toolchain

- src/Special/oslLoadImageFilePNG.c
- src/palette.c
Improvements Made:
1. Consistent Formatting: Improved indentation and spacing for better readability.
2. Removed Unused Code: Removed the unused oslPngFlushFn function.
3. Consistent Naming: Used consistent naming conventions for variables and functions.
4. Error Handling: Simplified error handling by grouping error conditions together.
5. Enhanced Comments: Added comments to clarify the purpose of different code sections.
6. Optimized Palette Handling: Simplified palette handling and color extraction.
> Improve oslLoadImageFilePNG code

- .vscode/c_cpp_properties.json
- src/text.c
1. **Function Enhancements**:
- **`oslLoadAltIntraFontFile`**:
- Added checks to ensure the font is of type `OSL_FONT_INTRA` before proceeding.
- Updated `intraFontSetStyle` and `intraFontSetAltFont` to handle alternative fonts properly.
- **`oslDeleteFont`**:
- Added null checks and improved resource cleanup by ensuring all dynamically allocated resources are freed properly.
- **`oslDrawTextTileBack`**:
- Updated to use `sceGuDrawArray` for rendering text background tiles with improved handling for texturing states.
- **`oslSetTextColor`** and **`oslSetBkColor`**:
- Simplified functions to set text and background colors.
- **`oslGetStringWidth`**:
- Added type checks to handle different font types (`OSL_FONT_OFT` and `OSL_FONT_INTRA`).
- Calculated string width based on font type, …
> Improve text class

- src/Special/oslLoadImageFileGIF.c
- Refactored and cleaned up the GIF loading code.
- Ensured memory management and image processing logic remain intact.
> Refactor GIF loading code

- .vscode/c_cpp_properties.json
- src/image/oslDrawImageSimple.c
Add comments to clarify the purpose of each section, making the code easier to understand
Improved indentation and alignment for readability
> Code formatting and document oslDrawImageSimple

- src/mem/oslGetRamStatus.c
- Optimized memory allocation handling by combining allocation and error checks.
- Simplified loops and reduced redundant comments for cleaner code.
> Refactor oslGetRamStatus

- src/audio.h
- src/bgm.h
**Description:**
This PR enhances the documentation for OSLib's audio management functions, improving clarity and consistency to aid developers.
**Key Updates:**
1. **Detailed Descriptions:** Added comprehensive explanations for functions and variables related to audio management.
2. **Documentation Structure:** Organized content into relevant groups (`audio_adv` and `audio`), and streamlined descriptions by removing non-essential example code.
3. **Doxygen Compliance:** Ensured all documentation comments are Doxygen-compatible for better integration into automated doc generation.
**Impact:**
These documentation improvements facilitate easier understanding and usage of OSLib's audio features, supporting better maintenance and development efficiency.
> Update Audio Management Documentation for OSLib

- src/audio.h
- src/bgm.h
- src/browser.h
This PR adds Doxygen documentation to the `browser.h` header file, enhancing the clarity and usability of the `Browser` module's functions and macros. The documentation covers the initialization process, memory handling, and status management for Sony's internet browser, making it easier for developers to understand and use these functions effectively.
- Added detailed descriptions for each function and macro in `browser.h`.
- Organized the documentation using Doxygen tags to ensure proper grouping and readability.
- Improved code maintainability and developer experience through clear, structured documentation.
- Facilitates better understanding and usage of the `Browser` module's API.
> Document Browser

- src/dialog.h
This PR adds Doxygen documentation to the `dialog.h` header file, enhancing the clarity and usability of the `Dialog` module's functions and macros. Making it easier for developers to understand and use these functions effectively.
- Added detailed descriptions for each function and macro in `dialog.h`.
- Organized the documentation using Doxygen tags to ensure proper grouping and readability.
- Improved code maintainability and developer experience through clear, structured documentation.
- Facilitates better understanding and usage of the `Dialog` module's API.
> Document Dialog

- src/emu.h
This PR adds comprehensive Doxygen documentation to the `emu.h` file. Key updates include:
- **Macros & Constants**: Documented all macros and OpenGL constants.
- **Types & Enums**: Provided descriptions for type definitions and enumerations.
- **Functions**: Added documentation for all function prototypes, covering parameters and return values.
- **Structures**: Detailed the fields of key structures like `SceCtrlData`.
- **Improved Clarity**: Enhances code understanding and maintainability.
- **Developer Experience**: Enables easy generation of reference documentation.
No functional changes were made; this PR is documentation-only.
> Document Emu

- src/net.h
This update introduces key functions and constants for managing network operations on the PSP.
- **APCTL States:** Defines states like `OSL_APCTL_STATE_DISCONNECTED`, `OSL_APCTL_STATE_SCANNING`, and more for managing Access Point connections.
- **Error Codes:** Adds comprehensive error codes (`OSL_NET_ERROR_*`, `OSL_ERR_*`) to handle network-related issues, including APCTL and HTTP errors.
- **Network Configuration:** Introduces `oslNetConfig` structure for storing network settings.
- **WLAN Management:** `oslIsWlanPowerOn()`, `oslIsWlanConnected()`
- **Network Initialization:** `oslNetInit()`, `oslNetTerm()`
- **AP Management:** `oslConnectToAP()`, `oslDisconnectFromAP()`, `oslGetAPState()`
- **Socket Operations:** Includes `oslNetSocketCreate()`, `oslNetSocketSend()`, and related …
> Document Net

- src/VirtualFile.h
- **Enhanced Documentation:**
- Updated file-level Doxygen comment to standardize the format.
- Added Doxygen comments to macros, structures, and external variables related to virtual file sources.
**Impact:**
- Improved clarity and maintainability of the virtual file system documentation in OSLib.
> Document VirtualFile

- src/ccc.h
- src/oslib.h
This PR enhances the `oslib.h` header file by adding comprehensive Doxygen-style documentation. The updates include:
- **File Overview**: Added a brief introduction to the file's purpose within OSLib.
- **Module Descriptions**: Grouped related functions and variables under clear sections (`general`, `sync`, `memory`, `maths`, `debug`, `misc`).
- **Detailed Documentation**: 
- Documented key variables, function pointers, and functions.
- Added explanations for macros, particularly those related to memory management and benchmarking.
- Clarified platform-specific differences between PSP and non-PSP environments.
- **No functional changes**.
- **Improved readability**: The documentation provides clear guidance for developers, making the library easier to use and maintain.
This PR prepares …
> Document oslib

- src/image/oslDrawImage.c
This PR refactors the `oslDrawImage` function to ensure C compatibility, improve performance, and clean up the code.
- Replaced C++-style initialization with explicit assignments for C compatibility.
- Optimized performance by precomputing sine and cosine values within the loop.
- Removed unused variables and addressed related warnings.
- Improved code readability by simplifying variable names and organizing related computations.
- Ensures compatibility with C compilers.
- Enhances performance and reduces computational overhead.
- Cleans up the code for better maintainability.
> Refactor `oslDrawImage` for C Compatibility and Performance

- src/osk.c
This PR refactors the OSK initialization and activation logic to improve code readability and memory management. Key changes include:
- Removed redundant variables and commented-out code for cleaner implementation.
- Enhanced memory management by ensuring proper allocation and deallocation of dynamic memory.
- Simplified the logic for text handling in OSK, including text input and output retrieval.
- Used consistent naming conventions and optimized string handling by using `size_t` for string lengths.
These changes aim to make the OSK code more maintainable, efficient, and easier to understand while preventing potential memory leaks.
> Refactor OSK Initialization and Memory Management

- src/messagebox.c
- Improved the `oslUIDrawButtonFrame` function for better button frame rendering, including gradient backgrounds and improved border and shadow effects.
- Updated the `oslMessageBox` function to better handle button rendering and text display with improved layout and functionality.
- Added descriptive comments for UI layout constants to enhance readability and maintainability.
- Improved error handling and code structure for more robust message box behavior.
> Enhance UI rendering and message box functionality

- samples/shapes/main.c
- samples/shapes/makefile
- src/shape.c
- Removed inconsistent coordinate adjustments in `oslDrawRect` for more accurate rendering.
- Fixed bitwise operation in `oslBlendColors` for correct color blending.
- Optimized `oslBlendColors` by pre-blending colors to reduce redundant computations.
- Simplified texture toggling with a helper function to eliminate repetition.
- Added coordinate validation in `oslDrawRect` to handle cases where `x1 < x0` or `y1 < y0`.
> Improve shape drawing functions for consistency and correctness

- src/splash/oslShowSplashScreen1.c
- Renamed functions and variables for clarity (e.g., shiftLogoPixels, createRotatingPalette)
- Optimized loop structures and conditional logic
- Improved comments for better code understanding
- Preserved original functionality, including animations and keypress handling
- Enhanced image processing for transparency and palette rotation
> refactor: improve OSLib splash screen code structure and readability

- src/audio/mod.c
- Optimized loop structures and conditional logic
- Improved comments for better code understanding
- Preserved original functionality
> Refactor audio mod

- src/keys.c
- Improved handling of analog stick and D-pad conversion
- Enhanced readability with consistent formatting and better variable naming
- Refined auto-repeat logic for both controller and remote input
- Initialized control data structures to prevent potential uninitialized memory usage
> Refactor and optimize input handling in OSL controller

- src/splash/oslShowSplashScreen2.c
- Added forward declarations for handlePhase, updateTileSpeeds, and drawLogo to avoid implicit declaration errors.
- Moved function definitions below oslShowSplashScreen2 for better organization and clarity.
- Improved code readability by dividing the functionality into smaller modular functions.
> Refactor oslShowSplashScreen2

- src/usb.c
- Modularized the loading of kernel modules using an array for easier maintenance
- Added safety checks before stopping and unloading modules
- Improved error handling during USB driver startup and capacity setting
- Enhanced code readability with consistent formatting and comments
- Ensured proper file system handling to prevent corruption on memory stick
> Refactor USB storage initialization and deinitialization
